### PR TITLE
Streamline webpack bundle

### PR DESCRIPTION
**Pull request by nickarora**
Not sure if this addresses the issues you were facing but take a look:

👉 streamlines the build process so that `dist` is self-sufficent.  Meaning, you can start with an empty `dist` folder and webpack will generate everything necessary for the library and demo when you build.  previously, demo relied on the assumption that `dist/rrule` was built in advance.

👉 `index.html` has been moved to the `demo` folder and just serves as a sortof "template".  To run the demo, open `dist/index.html` after building.

👉 `demo/demo.js` has been deleted.  Instead, webpack compiles the coffee script directly.

👉 the built `rrule` library is now named `dist/rrule.js`.  It was a little confusing having an `index.html` which was related to the demo and an `index.js` which was related to the library.

Finally, at least as far as testing with the demo applications goes, the source maps appear to work.

screen shot 2018-07-31 at 12 21 34 am

Here you can see I was doing some logging and chrome was referencing the line numbers in the pre-transpiled source code.  I was also able to throw errors from the source or set break points in it.

### CODE REVIEW

**Comment by davidgoli** [comment]
It's strange bc I was also seeing sourcemaps work from the demo app, but *not* when the package was `yarn link`ed as a node module from a different repo (eg. the weconnect repo's `rrule` package).

**Comment by aaronjensen** [comment]
> It's strange bc I was also seeing sourcemaps work from the demo app, but not when the package was yarn linked as a node module from a different repo (eg. the weconnect repo's rrule package).

What are you wanting the sourcemaps to map to? Your weconnect webpack would sourcemap to the file in `dist/` in this package, not to the original source. I don't know of a way to set up transitive source maps in that way. Is that what you're trying to do?

**Comment by nickarora** [comment]
In order to accomplish transitive source-maps, we might be able to use something like this?

https://github.com/webpack-contrib/source-map-loader

I haven't used it before but that change would have to happen in the weconnect app, not here

**Comment by aaronjensen** [comment]
well, I don't know that transitive source maps are as good an idea as pointing to the raw source and babeling it yourself. That said, I don't know what you're trying to do with this and I don't have much context.

**Comment by davidgoli** [comment]
@aaronjensen I like that approach better actually, I think this library *does* need to support transitive sourcemaps for web clients (unless maybe we don't need to webpack at all?), but otherwise we should try to provide the original es6 source instead, which is what I'd prefer.

**Comment by davidgoli** [comment]
For context, the immediate next thing here is going to be a typescript conversion in order to get some typechecking in place (because the original python code did a lot of tricky, hard-to-follow things such as reassigning different types to the same variable etc). I originally added webpack bc the original version of the repo was in es5 with its own, webpack-like polyglot import header (for amd, commonjs, etc), and the docs mention that you should be OK to just import this library in a script tag, so I was trying to preserve that. However, it's not clear how much of a requirement that still is in today's world.

**Comment by aaronjensen** [comment]
One other note: the thing in dist shouldn't be minified. I don't know if it is or not, but ideally it'd just be bundled and not minified. That way, even if you don't have transitive source maps it is still readable. 

I'd still recommend looking into parcel or rollup unless you want to go straight es6 (which is a thing people do now-a-days)

**Pull request merged**
